apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: service-aggregator-dr
  namespace: {{ .Release.Namespace }}
spec:
  host: service-aggregator-clusterip-service.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 2000  # 비동기 서비스는 높은 동시성 처리 가능
      http:
        http1MaxPendingRequests: 800  # 많은 요청을 대기할 수 있도록 증가
        maxRequestsPerConnection: 100  # Keep-Alive 연결에서 더 많은 요청 처리 가능
    outlierDetection:
      consecutive5xxErrors: 3  # 3번 연속 5xx 발생 시 해당 Pod을 배제
      interval: 5s  # 5초마다 상태 체크
      baseEjectionTime: 10s  # 장애 발생한 Pod을 10초 동안 배제 (빠른 복구)
      maxEjectionPercent: 40  # 전체 Pod 중 최대 40% 배제 가능
