apiVersion: 'v1'
kind: 'Service'
metadata:
  name: 'service-aggregator-clusterip-service'
spec:
  type: ClusterIP
  # type: NodePort
  selector:
    app: 'service-aggregator-container'
  ports:
  - protocol: 'TCP'
    port: 80
    targetPort: 8080

#
