apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: send-mail-job
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nine-docs/infra-manifest
    path: charts/batch/send-mail-job
    targetRevision: main
    helm:
      valueFiles:
      - ../../article/common_values.yaml
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
